on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build roBa
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZMK Build Action (Left)
        uses: zmkfirmware/zmk-action-build@v2
        with:
          board: seeeduino_xiao_ble
          shield: roba_left
          config_path: config

      - name: ZMK Build Action (Right)
        uses: zmkfirmware/zmk-action-build@v2
        with:
          board: seeeduino_xiao_ble
          shield: roba_right
          config_path: config
